{
 "title": "freebox-monitoring",
 "description": "Monitoring dashboard for the freebox delta.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Fans speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "freebox_fan_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Freebox start from",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "freebox_start_from", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Freebox version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "freebox_firmware_version_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time to create the metrics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "freebox_time_script", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection rate in byte/s",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "freebox_net_states", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "freebox_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lan browser",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "freebox_lan_browser_pub", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Switch in byte/s",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "freebox_switch_states", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Information storage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "freebox_storage_disk", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Port incoming",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    { "expr": "freebox_port_incoming", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Port forwarding",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    { "expr": "freebox_port_forwarding", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "VPN connection",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "targets": [
    { "expr": "freebox_vpn_connection", "legendFormat": "__auto" }
   ]
  }
 ]
}